"""Add hero_description to portfolio_config

Revision ID: 10d14105d688
Revises: 2d83030d2659
Create Date: 2026-03-29 12:57:45.340139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d14105d688'
down_revision = '2d83030d2659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_config', schema=None) as batch_op:
        batch_op.drop_column('hero_description')

    # ### end Alembic commands ###
