"""ajout du numero de telephon et de la description

Revision ID: 2c7a210e32c3
Revises: af33109ae34b
Create Date: 2026-02-10 23:40:21.957054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7a210e32c3'
down_revision = 'af33109ae34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone_principal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telephone_mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_column('telephone_mobile')
        batch_op.drop_column('telephone_principal')

    # ### end Alembic commands ###
