"""modification des projet

Revision ID: 44f8d387d2e9
Revises: f3ad5d22096d
Create Date: 2026-02-10 14:48:06.912819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44f8d387d2e9'
down_revision = 'f3ad5d22096d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('demo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_couverture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_projet', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('repo_id_github', sa.String(length=100), nullable=True))
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('projets_id_depot_github_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['repo_id_github'])
        batch_op.drop_column('est_visible')
        batch_op.drop_column('titre_personnalise')
        batch_op.drop_column('technologies')
        batch_op.drop_column('collaborateurs_et_orgs')
        batch_op.drop_column('url_depot')
        batch_op.drop_column('annee_creation')
        batch_op.drop_column('id_depot_github')
        batch_op.drop_column('description_personnalisee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_personnalisee', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_depot_github', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('annee_creation', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url_depot', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('collaborateurs_et_orgs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('technologies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titre_personnalise', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('est_visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('projets_id_depot_github_key'), ['id_depot_github'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('repo_id_github')
        batch_op.drop_column('logo_projet')
        batch_op.drop_column('image_couverture')
        batch_op.drop_column('demo_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('description')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
