"""modification des projet

Revision ID: 5516714d5e75
Revises: 44f8d387d2e9
Create Date: 2026-02-10 16:12:34.702627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5516714d5e75'
down_revision = '44f8d387d2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_collaboration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('structure_nom', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.drop_column('structure_nom')
        batch_op.drop_column('est_collaboration')

    # ### end Alembic commands ###
