"""ajout du numero du model portfolio

Revision ID: 83166a3e9341
Revises: 2c7a210e32c3
Create Date: 2026-02-11 21:19:46.916423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83166a3e9341'
down_revision = '2c7a210e32c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('hero_titre', sa.String(length=200), nullable=True),
    sa.Column('hero_sous_titre', sa.Text(), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_config')
    # ### end Alembic commands ###
