"""ajout du numero du model portfolio

Revision ID: 86621e491e34
Revises: ca8d7206d9cd
Create Date: 2026-02-12 15:08:38.482413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86621e491e34'
down_revision = 'ca8d7206d9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('hero_titre', sa.String(length=255), nullable=True),
    sa.Column('hero_texte', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('hero_bouton_1_texte', sa.String(length=100), nullable=True),
    sa.Column('hero_bouton_1_lien', sa.String(length=255), nullable=True),
    sa.Column('hero_bouton_2_texte', sa.String(length=100), nullable=True),
    sa.Column('hero_bouton_2_lien', sa.String(length=255), nullable=True),
    sa.Column('philosophie_titre', sa.String(length=255), nullable=True),
    sa.Column('philosophie_sous_titre', sa.String(length=255), nullable=True),
    sa.Column('philosophie_description_1', sa.Text(), nullable=True),
    sa.Column('philosophie_description_2', sa.Text(), nullable=True),
    sa.Column('philosophie_image_url', sa.String(length=500), nullable=True),
    sa.Column('values_json', sa.JSON(), nullable=True),
    sa.Column('parcours_json', sa.JSON(), nullable=True),
    sa.Column('competences_titre', sa.String(length=255), nullable=True),
    sa.Column('competences_sous_titre', sa.String(length=255), nullable=True),
    sa.Column('competences_image_url', sa.String(length=500), nullable=True),
    sa.Column('competences_json', sa.JSON(), nullable=True),
    sa.Column('certifications_titre', sa.String(length=255), nullable=True),
    sa.Column('certifications_sous_titre', sa.String(length=255), nullable=True),
    sa.Column('certifications_image_url', sa.String(length=500), nullable=True),
    sa.Column('certifications_json', sa.JSON(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_about_pages_utilisateur_id'), ['utilisateur_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_about_pages_utilisateur_id'))

    op.drop_table('about_pages')
    # ### end Alembic commands ###
