"""creation des migrations

Revision ID: 97dfffa2bfa6
Revises: 
Create Date: 2026-02-27 13:10:53.596246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dfffa2bfa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('hero_titre', sa.String(length=255), nullable=True),
    sa.Column('hero_texte', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('hero_bouton_1_texte', sa.String(length=100), nullable=True),
    sa.Column('hero_bouton_1_lien', sa.String(length=255), nullable=True),
    sa.Column('hero_bouton_2_texte', sa.String(length=100), nullable=True),
    sa.Column('hero_bouton_2_lien', sa.String(length=255), nullable=True),
    sa.Column('philosophie_titre', sa.String(length=255), nullable=True),
    sa.Column('philosophie_sous_titre', sa.String(length=255), nullable=True),
    sa.Column('philosophie_description_1', sa.Text(), nullable=True),
    sa.Column('philosophie_description_2', sa.Text(), nullable=True),
    sa.Column('philosophie_image', sa.String(length=500), nullable=True),
    sa.Column('parcours_image', sa.String(length=500), nullable=True),
    sa.Column('competences_titre', sa.String(length=255), nullable=True),
    sa.Column('competences_sous_titre', sa.String(length=255), nullable=True),
    sa.Column('competences_image', sa.String(length=500), nullable=True),
    sa.Column('certifications_titre', sa.String(length=255), nullable=True),
    sa.Column('certifications_sous_titre', sa.String(length=255), nullable=True),
    sa.Column('certifications_image', sa.String(length=500), nullable=True),
    sa.Column('values_json', sa.JSON(), nullable=True),
    sa.Column('parcours_json', sa.JSON(), nullable=True),
    sa.Column('competences_json', sa.JSON(), nullable=True),
    sa.Column('certifications_json', sa.JSON(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_about_pages_utilisateur_id'), ['utilisateur_id'], unique=False)

    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('jeton_github', sa.String(length=255), nullable=True),
    sa.Column('photo_profil', sa.String(length=255), nullable=True),
    sa.Column('photo_couverture', sa.String(length=255), nullable=True),
    sa.Column('cv', sa.String(length=255), nullable=True),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('poste', sa.String(length=100), nullable=True),
    sa.Column('localisation', sa.String(length=100), nullable=True),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('linkedin', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=100), nullable=True),
    sa.Column('github_access_token', sa.String(length=255), nullable=True),
    sa.Column('telephone_principal', sa.String(length=20), nullable=True),
    sa.Column('telephone_mobile', sa.String(length=20), nullable=True),
    sa.Column('theme_prefere', sa.String(length=20), nullable=True),
    sa.Column('est_confirme', sa.Boolean(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nom_utilisateur')
    )
    op.create_table('portfolio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('hero_titre', sa.String(length=200), nullable=True),
    sa.Column('about_titre', sa.String(length=200), nullable=True),
    sa.Column('about_soustitre', sa.String(length=200), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('about_lien_texte', sa.String(length=100), nullable=True),
    sa.Column('about_skills_json', sa.JSON(), nullable=True),
    sa.Column('tech_stack_json', sa.JSON(), nullable=True),
    sa.Column('projects_titre', sa.String(length=200), nullable=True),
    sa.Column('cta_titre', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('demo_url', sa.String(length=255), nullable=True),
    sa.Column('image_couverture', sa.String(length=255), nullable=True),
    sa.Column('logo_projet', sa.String(length=255), nullable=True),
    sa.Column('repo_id_github', sa.String(length=100), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('est_collaboration', sa.Boolean(), nullable=True),
    sa.Column('structure_nom', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('technologies_annexes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id_github')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projets')
    op.drop_table('portfolio_config')
    op.drop_table('utilisateurs')
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_about_pages_utilisateur_id'))

    op.drop_table('about_pages')
    # ### end Alembic commands ###
