"""ajout du numero du model portfolio

Revision ID: 9e9b50770973
Revises: 83166a3e9341
Create Date: 2026-02-11 21:49:58.854275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e9b50770973'
down_revision = '83166a3e9341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_titre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_soustitre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_lien_texte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('about_skills_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tech_stack_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('projects_titre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cta_titre', sa.String(length=200), nullable=True))
        batch_op.drop_column('tech_stack')
        batch_op.drop_column('hero_sous_titre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_sous_titre', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tech_stack', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('cta_titre')
        batch_op.drop_column('projects_titre')
        batch_op.drop_column('tech_stack_json')
        batch_op.drop_column('about_skills_json')
        batch_op.drop_column('about_lien_texte')
        batch_op.drop_column('about_soustitre')
        batch_op.drop_column('about_titre')

    # ### end Alembic commands ###
