"""ajout du numero du model portfolio

Revision ID: ca8d7206d9cd
Revises: 9e9b50770973
Create Date: 2026-02-11 23:03:54.974294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8d7206d9cd'
down_revision = '9e9b50770973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technologies_annexes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.drop_column('technologies_annexes')

    # ### end Alembic commands ###
