"""modification du model user

Revision ID: ed4aa6fefe6b
Revises: f9e58529f888
Create Date: 2026-02-10 18:06:59.144546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed4aa6fefe6b'
down_revision = 'f9e58529f888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True))
        batch_op.drop_column('derniere_connexion')

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_profil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo_couverture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poste', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('localisation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site_web', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('theme_prefere', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('derniere_connexion', sa.DateTime(), nullable=True))
        batch_op.drop_column('logo_profil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_profil', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('derniere_connexion')
        batch_op.drop_column('theme_prefere')
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('twitter')
        batch_op.drop_column('site_web')
        batch_op.drop_column('localisation')
        batch_op.drop_column('poste')
        batch_op.drop_column('photo_couverture')
        batch_op.drop_column('photo_profil')

    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('derniere_connexion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_mise_a_jour')
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###
