"""creation des migrations

Revision ID: f3ad5d22096d
Revises: 
Create Date: 2026-02-10 13:05:42.397063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ad5d22096d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('jeton_github', sa.String(length=255), nullable=True),
    sa.Column('logo_profil', sa.String(length=255), nullable=True),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('est_confirme', sa.Boolean(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nom_utilisateur')
    )
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_depot_github', sa.BigInteger(), nullable=True),
    sa.Column('titre_personnalise', sa.String(length=150), nullable=True),
    sa.Column('description_personnalisee', sa.Text(), nullable=True),
    sa.Column('annee_creation', sa.Integer(), nullable=True),
    sa.Column('url_depot', sa.String(length=255), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('collaborateurs_et_orgs', sa.JSON(), nullable=True),
    sa.Column('est_visible', sa.Boolean(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_depot_github')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projets')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
