"""ajout du numero du model me connaitre

Revision ID: f48abb7262b9
Revises: 86621e491e34
Create Date: 2026-02-12 15:40:59.882037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48abb7262b9'
down_revision = '86621e491e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('philosophie_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('parcours_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('competences_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('certifications_image', sa.String(length=500), nullable=True))
        batch_op.drop_column('certifications_image_url')
        batch_op.drop_column('competences_image_url')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('philosophie_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('philosophie_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hero_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('competences_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certifications_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('certifications_image')
        batch_op.drop_column('competences_image')
        batch_op.drop_column('parcours_image')
        batch_op.drop_column('philosophie_image')
        batch_op.drop_column('hero_image')

    # ### end Alembic commands ###
