"""ajout de la derniere connexion

Revision ID: f9e58529f888
Revises: 5516714d5e75
Create Date: 2026-02-10 16:51:47.779340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e58529f888'
down_revision = '5516714d5e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('derniere_connexion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.drop_column('derniere_connexion')

    # ### end Alembic commands ###
